# Config file for automatic testing at travis-ci.org

language: python
env:
  - TOXENV=py33
  - TOXENV=py34
install:
  - pip install codecov tox
script:
  - tox
after_success:
  - codecov
#  - make rtfd
